# Generated by Django 5.0.6 on 2024-06-03 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='type',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
